include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    # ferry graphql
    - "**/*.g.dart"
    - "**/*.ast.gql.dart"
    - "**/*.gql.dart"
    # freezed 
    - "**/*.freezed.dart"
    # https://www.fluttericon.com/
    - "**/app_icons.dart"
    # widgetbook
    - "lib/widgetbook/**"
    - "lib/main_widgetbook.dart"
  errors:
    flutter_style_todos: ignore
    library_private_types_in_public_api: ignore

custom_lint:
  rules:
    # Project uses [UncontrolledProviderScope] so we can disable this rule
    - missing_provider_scope: false
    # Disable this as we're still using old Provider for the GoRouter instance
    - avoid_manual_providers_as_generated_provider_dependency: false
linter:
  rules:
    public_member_api_docs: false
